version: '3.4'
services:
  sql_server:
    container_name: usersdb
    image: 'mcr.microsoft.com/mssql/server:2022-latest'
    ports:
      - '6000:1433'
    volumes:
      - 'users-db-volume:/var/lib/mssqlql/data/'
    env_file:
      - usersdb/usersdb.env
  dev-env:
    container_name: dev-env
    build:
      context: ./dev-env
    volumes:
      - '..:/workspace'
    stdin_open: true
    tty: true
volumes:
  users-db-volume: null
