version: '3.4'
services:
  sql_server:
    container_name: gatewaydb
    image: 'mcr.microsoft.com/mssql/server:2022-latest'
    ports:
      - '5000:1433'
    volumes:
      - 'gateway-db-volume:/var/lib/mssqlql/data/'
    env_file:
      - gatewaydb/gatewaydb.env
  dev-env:
    container_name: dev-env
    build:
      context: ./dev-env
    volumes:
      - '..:/workspace'
    stdin_open: true
    tty: true
volumes:
  gateway-db-volume: null
