version: '3.4'
services:
  usersdb:
    container_name: usersdb
    image: postgres:latest
    volumes:
      - 'users-db-volume:/var/lib/postgresql/data'
    env_file:
      - usersdb/usersdb.env
    ports:
      - 5432:5432
  spa:
    container_name: spa
    image: radoslawjakubowski/spa:latest
    ports: 
      - "4000:80"
    depends_on:
      - gateway
  rabbit:
    container_name: rabbitmq
    image: 'rabbitmq:latest'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    env_file:
      - rabbitmq/rabbitmq.env
  gateway:
    container_name: gateway
    image: 'radoslawjakubowski/gateway:latest'
    ports:
      - 5100:80
    depends_on:
      - rabbit
  users:
    container_name: users
    image: 'radoslawjakubowski/users:latest'
    depends_on:
      - usersdb
      - gateway
    restart: always
  notifications:
    container_name: notifications
    image: 'radoslawjakubowski/notifications:latest'
    depends_on:
      - gateway
volumes:
  users-db-volume: null
  rabbitmq_data: null