version: '3.4'
services:
  usersdb:
    container_name: usersdb
    image: postgres:latest
    volumes:
      - 'users-db-volume:/var/lib/postgresql/data'
    env_file:
      - usersdb/usersdb.env
  rabbit:
    container_name: rabbitmq
    image: 'rabbitmq:latest'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    env_file:
      - rabbitmq/rabbitmq.env
  dev-env:
    container_name: dev-env
    build:
      context: ./dev-env
    volumes:
      - '..:/workspace'
    stdin_open: true
    tty: true
volumes:
  users-db-volume: null
  rabbitmq_data: null
  pgadmin_data: null
